### ISSUE TITLE
Rails Resources

### ISSUE THREAD

**Issue by danlourenco** [MarcoMorawec/SiB-Dev-Team#20]
Hey guys, I am compiling a list of helpful Rails resources.  Feel free to add or contribute anything you find useful here and I'll add them to my blog.

http://blog.danlourenco.com/blog/2013/07/05/rails-resources/

**Comment by bpowell123** [comment]
Gems
https://www.ruby-toolbox.com/
http://rubygems.org/

Git
http://gitref.org/
http://git-scm.com/doc

**Comment by danlourenco** [comment]
Thanks, Brad. Added those.

**Comment by scit106** [comment]
Just found this super helpful site:

http://ruby.bastardsbook.com/toc/

**Comment by danlourenco** [comment]
good find! I'll add it to the blog

On Sun, Jul 21, 2013 at 11:50 AM, scit106 notifications@github.com wrote:

> Just found this super helpful site:
> 
> http://ruby.bastardsbook.com/toc/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MarcoMorawec/SiB-Dev-Team/issues/20#issuecomment-21312055
> .

## 

Dan Lourenco
Web Development Student
@MyNameIsDLo https://twitter.com/MyNameIsDLo |
@StartupInsthttp://www.twitter.com/startupinst

http://www.startupinstitute.com/

Check it out!
site http://www.startupinstitute.com/ |
bloghttp://blog.startupinstitute.com/
 | facebook http://www.facebook.com/startupinst
